name: 📦 Backport to develop
on:
  pull_request:
    types: [closed]
    branches:
      - 'release'
      - 'production'
env:
  GH_TOKEN: ${{ secrets.PAT }}
  GIT_AUTHOR_NAME: "Pubtex machine user"
  GIT_AUTHOR_EMAIL: "github-system@g.sys.pubtex.com"
  GIT_COMMITTER_NAME: "Pubtex machine user"
  GIT_COMMITTER_EMAIL: "github-system@g.sys.pubtex.com"

permissions: 
  contents: 'write'

jobs:
  backport:
    if: github.event.pull_request.merged && github.event.pull_request.head.ref != 'develop' && github.event.pull_request.head.ref != 'release'
    runs-on: pub-hub
    steps:
      - name: 🔜 Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: develop

      - name: 🔜 Create backport branch
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          BASE_BRANCH="develop"
          HEAD_BRANCH=${{ github.event.pull_request.base.ref }}

          cd scripts && ./backport.sh $PR_NUMBER $BASE_BRANCH $HEAD_BRANCH 
