name: Backport to develop
on:
  pull_request:
    types: [closed]
    branches:
      - 'release'
      - 'production'
env:
  GH_TOKEN: ${{ secrets.PAT }}
  GIT_AUTHOR_NAME: "GitHub Actions"
  GIT_AUTHOR_EMAIL: "actions@github.com"
  GIT_COMMITTER_NAME: "GitHub Actions"
  GIT_COMMITTER_EMAIL: "actions@github.com"

permissions: 
  contents: 'write'

jobs:
  backport:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: develop

      - name: test
        run:
          echo "${{ github.event.pull_request.merged }}"

      - name: Create backport branch
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          SOURCE_BRANCH="develop"

          cd scripts && ./backport.sh $PR_NUMBER $SOURCE_BRANCH ${{ github.event.pull_request.html_url }}
