on:
  pull_request:
    types: [labeled]
    branches:
      - 'develop'
env:
  GH_TOKEN: ${{ secrets.PAT }}

jobs:
  merge-backport:
    runs-on: ubuntu-latest
    steps:
      - name: 🔜 Checkout
        uses: actions/checkout@v4

      - name: Merge
        if: github.event.label.name == 'backport' && github.event.pull_request.head.ref == 'release'
        run: |
          gh pr merge ${{ github.event.number }} --rebase
